services:
  auth:
    image: 'ghcr.io/geiier/e-journal-auth:master'
    ports:
      - '8081:8081'
    environment:
      - 'POSTGRES_PASSWORD=13112001UJL'
      - 'POSTGRES_USER=geller'
  journal:
    image: 'ghcr.io/geiier/e-journal-back:master'
    ports:
      - '8082:8082'
    environment:
      - 'POSTGRES_PASSWORD=13112001UJL'
      - 'POSTGRES_USER=geller'
  front:
    image: 'ghcr.io/geiier/e-journal-front:master'
    ports:
      - '80:80'
      - '443:443'
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=journal'
      - 'POSTGRES_PASSWORD=13112001UJL'
      - 'POSTGRES_USER=geller'
    ports:
      - '5454:5432'