services:
  discovery:
    image: 'ghcr.io/geiier/e-journal-discovery:master'
    ports:
      - '8761:8761'
  auth:
    container_name: 'auth'
    image: 'ghcr.io/geiier/e-journal-auth:master'
    ports:
      - '8081:8081'
    environment:
      - 'POSTGRES_URL=jdbc:postgresql://postgres:5432/journal'
      - 'POSTGRES_PASSWORD=13112001UJL'
      - 'POSTGRES_USER=geller'
      - 'EUREKA_URI=http://discovery:8761/eureka'
  journal:
    container_name: 'journal'
    image: 'ghcr.io/geiier/e-journal-back:master'
    ports:
      - '8082:8082'
    environment:
      - 'POSTGRES_PASSWORD=13112001UJL'
      - 'POSTGRES_USER=geller'
      - 'EUREKA_URI=http://discovery:8761/eureka'
  front:
    image: 'ghcr.io/geiier/e-journal-front:master'
    ports:
      - '80:80'
      - '443:443'
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=journal'
      - 'POSTGRES_PASSWORD=13112001UJL'
      - 'POSTGRES_USER=geller'
    ports:
      - '5454:5432'