services:
  front:
    image: 'ghcr.io/geiier/e-journal-front:master'
    ports:
      - '80:80'
      - '443:443'
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=journal'
      - 'POSTGRES_PASSWORD=13112001UJL'
      - 'POSTGRES_USER=geller'
    ports:
      - '5454:5432'