spring:
  application:
    name: service_auth
  datasource:
    url: jdbc:postgresql://postgres:5432/journal
    password: '${POSTGRES_PASSWORD}'
    username: '${POSTGRES_USER}'
  jpa:
    hibernate:
      ddl-auto: update
  data:
    jdbc:
      dialect: postgresql

server:
  port: 8081

security:
  jwt:
    secret:
      access: "asdajdlajijpoiajdaeruyph;ds.bv/d\aw'ewr437eflkasfj3r-vbjxdcs3tr]pfkbwdgfiucrt]3-0"
      refresh: "jkhsdgg';klsadgpojaerhpojdfb[pkeargpojdfb[psdfjwerpojdfhjxpojwejpopojsdfokiweg[f"
    issuer: "http://authService"

