spring:
  application:
    name: e-journal-auth
  datasource:
    url: '${POSTGRES_URL}'
    password: '${POSTGRES_PASSWORD}'
    username: '${POSTGRES_USER}'
  jpa:
    hibernate:
      ddl-auto: update
  data:
    jdbc:
      dialect: postgresql

server:
  port: 8081

security:
  jwt:
    secret:
      access: "asdajdlajijpoiajdaeruyph;ds.bv/d\aw'ewr437eflkasfj3r-vbjxdcs3tr]pfkbwdgfiucrt]3-0"
      refresh: "jkhsdgg';klsadgpojaerhpojdfb[pkeargpojdfb[psdfjwerpojdfhjxpojwejpopojsdfokiweg[f"
    issuer: "http://authService"

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}:${server.port}
  instance:
    preferIpAddress: true